accounts/urls.py
from django.urls import path,include
from .import views
urlpatterns = [
    
    path('signup/',views.signup_user,name=""),
    path('login/',views.login_user,name='')

    
]

e_commerce/urls.py
from django.urls import path,include
from .import views
urlpatterns = [
    path('',views.index,name=''),
    path('contect-us/',views.contect_us,name=''),
    path('about-us/',views.about,name='about'),
    path('all-about-us/',views.all_about,name='about'),
    path('our-progress/',views.our_progress,name='progress'),
    path('our-purpose/',views.our_purpose,name='purpose'),
    path('our-value/',views.our_value,name='value'),
    path('vission-mission/',views.vission_and_mission,name='vision'),
    path('our-hitory/',views.our_history,name='history'),
    # path('brand/',views.brand_view,name='brand'),
    
    path('products/<int:subcategory_id>/',views.product_list, name='product_list'),
    
    

    
    

    
]

hertes_food_products_pvt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/",include("accounts.urls")),
    path("",include("e_commerce.urls")),
    

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

e_commerce/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name
class Sub_category(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
class Brand(models.Model):
    name = models.CharField(max_length=150)
    image =models.ImageField(upload_to='about/',blank=True,null=True)
    text = models.TextField()
    timedate = models.DateTimeField(auto_now_add=True, blank=True)
class product(models.Model):
    Available =(
        ('In stack','In stack'),
        ('Out of stack','Out of stack')
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    sub_category = models.ForeignKey(Sub_category, on_delete=models.CASCADE)
    available  = models.CharField(max_length = 100,choices =Available,null ='True')
    image = models.ImageField(upload_to='Ecommerce/ping')
    name = models.CharField(max_length=100)
    text = models.TextField()
    price = models.IntegerField()
    
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name
class about_us(models.Model):
    name = models.CharField(max_length=150,blank=True,null=True)
    image =models.ImageField(upload_to='about/',blank=True,null=True)
    text = models.TextField()
    timedate = models.DateTimeField(auto_now_add=True, blank=True)
class all_about_us(models.Model):
    image =models.ImageField(upload_to='all_about/',blank=True,null=True)
    text = models.TextField()
    timedate = models.DateTimeField(auto_now_add=True, blank=True)
class vision_mission(models.Model):
    image =models.ImageField(upload_to='vision_&_misson',blank=True,null=True)
    text = models.TextField()
    timedate = models.DateTimeField(auto_now_add=True, blank=True)
class history(models.Model):
    image =models.ImageField(upload_to='vision_&_misson',blank=True,null=True)
    text = models.TextField()
    timedate = models.DateTimeField(auto_now_add=True, blank=True)
class Our_purpose(models.Model):
    image =models.ImageField(upload_to='vision_&_misson',blank=True,null=True)
    text = models.TextField()
    timedate = models.DateTimeField(auto_now_add=True, blank=True)
class Our_value(models.Model):
    image =models.ImageField(upload_to='vision_&_misson',blank=True,null=True)
    text = models.TextField()
    timedate = models.DateTimeField(auto_now_add=True, blank=True)
class Our_progress(models.Model):
    image =models.ImageField(upload_to='vision_&_misson',blank=True,null=True)
    text = models.TextField()
    timedate = models.DateTimeField(auto_now_add=True, blank=True)


class Slidingimage(models.Model):
    name = models.CharField(max_length=150)
    image =models.ImageField(upload_to='sliding/image',blank=True,null=True)
    txt = models.TextField()
class Slidingimagebrand(models.Model): 
    image =models.ImageField(upload_to='sliding/image',blank=True,null=True)
   

e_commerce/views.py
from django.shortcuts import render
from .models import about_us,all_about_us,Our_progress,Our_purpose,Our_value,vision_mission,history,\
Slidingimage,Slidingimagebrand,product,Category,Brand
# Create your views here.

def index(request):
    slid_obj=Slidingimage.objects.all()
    slid_obj_brand=Slidingimagebrand.objects.all()
    category= Category.objects.all()
    brand_obj=Brand.objects.all()
    CategoryId = request.GET.get('category')
    if CategoryId:
        product_obj = product.objects.filter(sub_category=CategoryId).order_by('-id')
    else:
        product_obj=product.objects.all()
    context={
        'product':product_obj,
        'category':category,
        'brand':brand_obj,
        'first_slid':slid_obj,
        'slid_second':slid_obj_brand,
    }
    return render(request,'kk.html',context)
#
def product_list(request, subcategory_id):
    products = product.objects.filter(sub_category=subcategory_id)
    slid_obj_brand=Slidingimagebrand.objects.all()
    slid_obj=Slidingimage.objects.all()
    context={
        "products":products,
        "slid_second":slid_obj_brand,
        'first_slid':slid_obj,

    }
    return render(request, 'product_list.html',context)
#
#
#
def about(request):
    about_obj = about_us.objects.all()
    return render(request,'about_us/about_us.html',{'about':about_obj})
#
def our_value(request):
    slid_obj_brand=Slidingimagebrand.objects.all()
    value_obj = Our_value.objects.all()

    context={
       
        'slid_second':slid_obj_brand,
        'about':value_obj,
    }
    return render(request,'about_us/our_values.html',context)
#
def our_progress(request):
    slid_obj_brand=Slidingimagebrand.objects.all()
    about_obj = Our_progress.objects.all()

    context={
       
        'slid_second':slid_obj_brand,
        'about':about_obj,
    }
    return render(request,'about_us/our_purpose.html',context)
#
def vission_and_mission(request):
    slid_obj_brand=Slidingimagebrand.objects.all()
    about_obj = vision_mission.objects.all()

    context={
       
        'slid_second':slid_obj_brand,
        'about':about_obj
    }
    return render(request,'about_us/vision_&_mission.html',context)
#
def our_purpose(request):
    slid_obj_brand=Slidingimagebrand.objects.all()
    about_obj = Our_purpose.objects.all()

    context={
       
        'slid_second':slid_obj_brand,
        'about':about_obj,
    }
    return render(request,'about_us/our_purpose.html',context)
#
def our_history(request):
    slid_obj_brand=Slidingimagebrand.objects.all()
    history_obj = history.objects.all()

    context={
       
        'slid_second':slid_obj_brand,
        'about':history_obj,
    }
    return render(request,'history.html',context)

#
def all_about(request):
    slid_obj_brand=Slidingimagebrand.objects.all()
    about_obj = all_about_us.objects.all()

    context={
       
        'slid_second':slid_obj_brand,
        'about':about_obj,
    }
    return render(request,'about_us/all_about_us.html',context)
#
def contect_us(request):
    slid_obj_brand=Slidingimagebrand.objects.all()

    context={
       
        'slid_second':slid_obj_brand,
    }
    return render(request,'conteck_us.html')
#

e_commerce/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% block content1 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    

<header >
<!--     
  <div class="">
    <div class="d-md-flex justify-content-between align-items-center">
      
          <div class="switch-css">
            <label class="switch">
              <input type="checkbox" id="toggle" />
              <span class="slider round"></span>
            </label>
         
    </div>
  </div> -->
  <div style="border: 1px solid rgb(204, 237, 155); background-color: rgb(132, 199, 24); padding: 5px;">
    <center>
    <h5 style="color: white;">Love in Every Quality</h5>
</center>
    <!-- Content of the second container -->
</div>
  <nav class="navbar py-0 navbar-expand-lg"  style="margin-top: -.9896rem;">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <img class=" img-fluid" src="{% static 'assets/images/logo.png' %}" alt="Hertes Logo" style="height: 70px; margin-top: 0.36rem;">
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <form class="d-flex align-items-center border-bottom" role="search" style="width: 300px; border-radius: 50px; color: chartreuse;">
            <input class="form-control bg-transparent border-0 me-2" style="color: rgb(245, 246, 244);" type="search" placeholder="Search"
                   style="border-radius: 50px 0 0 50px; width: 100%;"
                   aria-label="Search" />
            <button type="submit" class="btn bg-transparent border-0" style="border-radius: 0 50px 50px 0; ">
              <img src="{% static 'assets/images/Search-Icon.svg' %}" class="search-icon"
                   style="width: 25px; height: 25px; border-radius: 50%; object-fit: cover; color: chartreuse;" alt="Search Icon" />
            </button>
          </form>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a class="navbar-brand text-black" href="/">
            <i class="fas fa-home" style="color: rgb(132, 199, 24); font-size: 1.5rem;"></i>
          </a>
          
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#main_nav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="main_nav">
        <ul class="navbar-nav ">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle"  role="button" aria-expanded="false"style="color: chartreuse;">About us</a>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item"  href="/all-about-us/" style="color: rgb(132, 199, 24);">Go to About Us</a>
              </li>
            
              <li>
                <a class="dropdown-item" href="/vission-mission/" style="color: rgb(132, 199, 24);">Vision & Mission</a>
              </li>
              <li>
                <a class="dropdown-item" href="/our-purpose/" style="color: rgb(132, 199, 24);">Our Purpose</a>
              </li> 
              <li>
                <a class="dropdown-item" href="/our-value/" style="color: rgb(132, 199, 24);">Our progress</a>
              </li>
             
            </ul>
            
          </li>
          <div class="mt4" style="margin-top: -.36rem;">
          <ul class="navbar">
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" role="button" aria-expanded="false" style="color: rgb(132, 199, 24);">Our business</a>
                  <ul class="dropdown-menu">
                      <li>
                          <a class="dropdown-item" href="#" style="color: rgb(132, 199, 24);">Go to Our business</a>
                      </li>
                      {% for cat in category %}
    <li class="dropdown-submenu">
        <a class="dropdown-item" href="{{ cat.id }}" style="color: rgb(132, 199, 24);"> {{ cat.name }}</a>
        {% for subcat in cat.sub_category_set.all %}
            <ul class="dropdown-menunested">
                <li>
                    <a class="dropdown-item" href="{% url 'product_list' subcategory_id=subcat.id %}" style="color: chartreuse;">
                        {{ subcat.name }}
                    </a>
                </li>
            </ul>
        {% endfor %}
    </li>
{% endfor %}
                      
                  </ul>
              </li>
          </ul>
          </div>
          <li class="nav-item">
            <a class="nav-link" href="/our-hitory/" style="color: rgb(132, 199, 24);">Our Stories</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#" style="color: rgb(132, 199, 24);">Shop</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#" style="color: rgb(132, 199, 24);">Media</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  
</header>
{% endblock %}
{% block content %}

<main style="margin-top: -4rem;">
  <div id="carouselExampleCaptions" class="carousel slide slider" data-bs-ride="carousel">
    <div class="carousel-indicators">
      {% for i in first_slid %}
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active" aria-current="true"{% endif %} aria-label="Slide {{ forloop.counter }}">
      </button>
      {% endfor %}
    </div>
    
    <div class="carousel-inner">
      {% for slide in first_slid %}
      <div class="carousel-item {% if forloop.first %}active{% endif %}">
        <img src="{{ slide.image.url }}" class="d-block w-100" alt="" />
        <div class="carousel-caption d-none d-md-block">
          <h2>{{ slide.name }}</h2>
          <p>{{ slide.txt|safe }}</p>
          <a href="#" class="mb-3">READ MORE
            <i class="fa ms-2 fa-arrow-right" aria-hidden="true"></i>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
      
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</main>
<section>
  <div class="py-4 container">
    <div class="row justify-content-center align-items-center g-3">
      {% for br in brand  %}
      <div class="col-md-3">
        <div class="card shadow" style="height: 500px">
          <img
            src="{{ br.image.url}}"
            class="card-img-top"
            alt=""
            style="width: 265px; height: 265px;"
          />
          <div class="card-body">
            <h4 class="card-title text-blue">{{ br.name }}</h4>
            <p class="card-text text-truncate2"style="text-shadow: 2px 2px 4px rgba(0,0,0,0.3); margin-top: -.96rem;">
              {{ br.text|safe|slice:":265" }}
            </p>
            <a
              href="#"
              style="bottom: 10px"
              class="text-blue position-absolute stretched-link"
              >READ MORE &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              
              {{ br.timedate }}
              {% comment %} <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                fill="currentColor"
                class="bi bi-arrow-right-short"
                viewBox="0 0 16 16"
              > {% endcomment %}
              
                <path
                  fill-rule="evenodd"
                  d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8"
                />
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
      <!-- Repeat the above code block for the remaining three images -->
    </div>
  </div>
</section>
       {% comment %} # {% endcomment %}
       <div class="py-3 text-center container">
        <center>
          <h5 class="green-text">𝓓𝓔ℒ𝓥𝓔 <span class="inline-text">INTO&nbsp; &nbsp;&nbsp;OUR&nbsp;&nbsp;&nbsp;OTHER&nbsp;&nbsp;&nbsp;BRANDS</span></h5>

        <div class="slick-slider brands-slider">
          {% for i in slid_second %}
          <a href="/assets/brand-details.html">
            <img src="{{ i.image.url }}" class="img-fluid shadow" alt="" />
          </a>
          {% endfor %}
        </center>

        </div>
        <center>
          <a href="#" class=" btn btn-primary " style="margin-top: -.96rem;">View all brands
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
              class="bi bi-arrow-right-short" viewBox="0 0 16 16">
              <path fill-rule="evenodd"
                d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8" />
            </svg>
          </a>
        </a>
      </center>
      </div>
        {% endblock %}
  </body>
  </html>

e_commerce/templates/ll.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% block content1 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

<header class="bg-white">
    
  <div class="py-md-4 py-2 container">
    <div class="d-md-flex justify-content-between align-items-center">
      <img width="140" src="{% static 'assets/images/hertes100.jpg' %}" class="img-fluid" />
      <div class="d-md-flex align-items-center gap-3">
        <form class="d-flex align-items-center border-bottom" role="search">
          <input class="form-control bg-transparent border-0 me-2" type="search" placeholder="Search"
            aria-label="Search" />
          <img width="25" src="{% static 'assets/images/Search-Icon.svg' %}" class="img-fluid search-icon" />
        </form>
        <div class="d-flex mt-md-0 mt-3 gap-3 align-items-center">
          <a href="/contect-us/" class="btn btn-primary">Contact us</a>
          <div class="switch-css">
            <label class="switch">
              <input type="checkbox" id="toggle" />
              <span class="slider round"></span>
            </label>
          </div>
        </div>
      </div>
    </div>
  </div>
  <nav class="navbar py-0 navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="/"
        ><i class="fas text-black fa-home"></i
      ></a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#main_nav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="main_nav">
        <ul class="navbar-nav ">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle"  role="button" aria-expanded="false">About us</a>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item" href="/all-about-us/">Go to About Us</a>
              </li>
            
              <li>
                <a class="dropdown-item" href="/vission-mission/">Vision & Mission</a>
              </li>
              <li>
                <a class="dropdown-item" href="/our-purpose/">Our Purpose</a>
              </li> 
              <li>
                <a class="dropdown-item" href="/our-value/">Our Value</a>
              </li>
               <li>
                <a class="dropdown-item" href="/our-progress/">Our progress</a>
              </li>
             
            </ul>
            
          </li>
          <div class="mt4" style="margin-top: -.36rem;">
          <ul class="navbar">
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" role="button" aria-expanded="false">Our business</a>
                  <ul class="dropdown-menu">
                      <li>
                          <a class="dropdown-item" href="#">Go to Our business</a>
                      </li>
                      {% for cat in category %}
    <li class="dropdown-submenu">
        <a class="dropdown-item" href="{{ cat.id }}">{{ cat.name }}</a>
        {% for subcat in cat.sub_category_set.all %}
            <ul class="dropdown-menunested">
                <li>
                    <a class="dropdown-item" href="{% url 'product_list' subcategory_id=subcat.id %}">
                        {{ subcat.name }}
                    </a>
                </li>
            </ul>
        {% endfor %}
    </li>
{% endfor %}
                      
                      {% comment %} <li class="dropdown-submenu">
                          <a class="dropdown-item" href="#">Arrocos</a>
                          <ul class="dropdown-menunested">
                              <li><a class="dropdown-item" href="#">Coffee decoction</a></li>
                              <li><a class="dropdown-item" href="#">Presence Across India</a></li>
                              <li><a class="dropdown-item" href="#">Research and Development</a></li>
                          </ul>
                      </li> {% endcomment %}
                      {% comment %} <li class="dropdown-submenu">
                          <a class="dropdown-item" href="#">Hertes Fitlys</a>
                          <ul class="dropdown-menunested">
                              <li><a class="dropdown-item" href="#">Millet- based snacks</a></li>
                              <li><a class="dropdown-item" href="#">Presence Across India</a></li>
                              <li><a class="dropdown-item" href="#">Research and Development</a></li>
                          </ul>
                      </li> {% endcomment %}
                  </ul>
              </li>
          </ul>
          </div>
          <li class="nav-item">
            <a class="nav-link" href="/our-hitory/">Our Stories</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Shop</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Media</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  
</header>
{% endblock %}
{% block content %}

<main>
  <div id="carouselExampleCaptions" class="carousel slide slider" data-bs-ride="carousel">
    <div class="carousel-indicators">
      {% for i in first_slid %}
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active" aria-current="true"{% endif %} aria-label="Slide {{ forloop.counter }}">
      </button>
      {% endfor %}
    </div>
    
    <div class="carousel-inner">
      {% for slide in first_slid %}
      <div class="carousel-item {% if forloop.first %}active{% endif %}">
        <img src="{{ slide.image.url }}" class="d-block w-100" alt="" />
        <div class="carousel-caption d-none d-md-block">
          <h2>{{ slide.name }}</h2>
          <p>{{ slide.txt|safe }}</p>
          <a href="#" class="mb-3">READ MORE
            <i class="fa ms-2 fa-arrow-right" aria-hidden="true"></i>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
      
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</main>
<section>
  <div class="py-4 container">
    <div class="row justify-content-center align-items-center g-3">
      {% for br in brand  %}
      <div class="col-md-3">
        <div class="card shadow" style="height: 500px">
          <img
            src="{{ br.image.url}}"
            class="card-img-top"
            alt=""
            style="width: 265px; height: 265px;"
          />
          <div class="card-body">
            <h4 class="card-title text-blue">{{ br.name }}</h4>
            <p class="card-text text-truncate2"style="text-shadow: 2px 2px 4px rgba(0,0,0,0.3); margin-top: -.96rem;">
              {{ br.text|safe|slice:":265" }}
            </p>
            <a
              href="#"
              style="bottom: 10px"
              class="text-blue position-absolute stretched-link"
              >READ MORE &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              
              {{ br.timedate }}
              {% comment %} <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                fill="currentColor"
                class="bi bi-arrow-right-short"
                viewBox="0 0 16 16"
              > {% endcomment %}
              
                <path
                  fill-rule="evenodd"
                  d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8"
                />
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
      <!-- Repeat the above code block for the remaining three images -->
    </div>
  </div>
</section>
       {% comment %} # {% endcomment %}
       <div class="py-3 text-center container">
        <center>
        <div class="slick-slider brands-slider">
          {% for i in slid_second %}
          <a href="/assets/brand-details.html">
            <img src="{{ i.image.url }}" class="img-fluid shadow" alt="" />
          </a>
          {% endfor %}
        </center>

        </div>
        <center>
          <a href="#" class=" btn btn-primary " style="margin-top: -.96rem;">View all brands
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
              class="bi bi-arrow-right-short" viewBox="0 0 16 16">
              <path fill-rule="evenodd"
                d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8" />
            </svg>
          </a>
        </a>
      </center>
      </div>
        {% endblock %}
  </body>
  </html>